### ISSUE TITLE
1.1.1版本wordpress会自动提示更新

### ISSUE THREAD

**Issue by AllenBall** [SpacePack/Snape#2]
wordpress里更新后，仍然提示更新：您正在使用的是版本。升级至1.1.1。

**Comment by lydasia** [comment]
似乎识别不出来当前主题的版本号，所以不断提示更新，应该在某个地方添加一下版本号就没问题了。

**Comment by Vtrois** [comment]
试着检测一下目录权限，看一下是否出现两个主题。版本在style.css的Version处控制
